### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Valerie-myk** [Valerie-myk/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by igorLyk** [comment]
<h3><a id="user-content-donald-trump" class="anchor" aria-hidden="true" href="#donald-trump"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" ></path></svg></a>DONALD TRUMP</h3>
<ul>
<li><a href="https://www.fb.com/DonaldTrump" rel="nofollow">https://www.fb.com/DonaldTrump</a></li>
<li><a href="mailto:realDonaldTrump@whitehouse.gov">realDonaldTrump@whitehouse.gov</a></li>
<li><a href="https://twitter.com/realDonaldTrump" rel="nofollow">https://twitter.com/realDonaldTrump</a></li>
<li><a href="https://www.instagram.com/realDonaldTrump/" rel="nofollow">https://www.instagram.com/realDonaldTrump/</a></li>
</ul>
